################################################################################
# Copyrights Â© 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
- sections:
  - title: Add Account
    link: docs/add-account.md
- sections:
  - title: AllData WS API
    link: docs/alldata-ws-api.md
    sections:
    - title: Overview
      link: docs/ws-api/overview.md
    - title: Integrations
      link: docs/ws-api/integrations.md
    - title: Web Services & APIs
      link: docs/ws-api/webservices-apis.md
    - title: Appendices
      link: docs/ws-api/appendices.md
- sections:
  - title: AllData Next-Gen
    link: docs/alldata-next-gen.md
    sections:
    - title: Overview
      link: docs/alldata-next-gen/overview-integration-approach.md
    - title: Widgets
      link: docs/alldata-next-gen/widgets.md
    - title: Implementation Approaches
      link: docs/alldata-next-gen/implementation-approaches.md
    - title: Appendices
      link: docs/alldata-next-gen/appendices.md
- sections:
  - title: AllData Common Use Cases API Solution
    link: docs/alldata-common-use-cases.md
